name: Deploy Master

on: 
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build
      run: |
        sudo chmod 777 gradlew
        ./gradlew jsWebMinWebpack
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.push }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: build/web-min-webpack
        GITHUB_REPOSITORY: jihuayu/korge-game
